version: '3.8'

services:
  # 1. Base de données MongoDB
  mongodb:
    image: mongo:latest
    container_name: app_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Interface graphique (Remplace pgAdmin) - Accessible via http://localhost:8081
  mongo-express:
    image: mongo-express
    container_name: app_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    depends_on:
      - mongodb

  # 3. Backend (User-Service)
  backend:
    build:
      context: ./backend/User-Service
    container_name: app_backend
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      # URL de connexion interne (Docker à Docker)
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/KidneyDatabase?authSource=admin

  # 4. Frontend
  frontend:
    build: ./frontend/careTemplate
    container_name: app_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mongo_data: