version: '3.8'

services:
  # 1. Base de données MongoDB
  mongodb:
    image: mongo:latest
    container_name: app_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Interface graphique (Remplace pgAdmin) - Accessible via http://localhost:8081
  mongo-express:
    image: mongo-express
    container_name: app_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    depends_on:
      - mongodb

  # 3. Backend (User-Service)
  backend:
    build:
      context: ./backend/User-Service
    container_name: app_backend
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      # URL de connexion interne (Docker à Docker)
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/KidneyDatabase?authSource=admin

                  #------Rania-------
  # --- Service 1 : Tracking ---
  tracking-service:
    build:
      context: Tracking-Service
    container_name: tracking-service
    ports:
      - "9011:9011"
    depends_on:
      - db-tracking
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-tracking:3306/db_tracking?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      # IMPORTANT : On utilise le nom du service docker ici
      - GEOFENCING_SERVICE_URL=http://geofencing-service:9012
    restart: always

  db-tracking:
    image: mysql:8.0
    container_name: db-tracking
    environment:
      MYSQL_DATABASE: db_tracking
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  # --- Service 2 : Geofencing ---
  geofencing-service:
    build:
      context: ./backend/Geofencing-Service
    container_name: geofencing-service
    ports:
      - "9012:9012"
    depends_on:
      - db-geofencing
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-geofencing:3306/db_geofencing?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    restart: always

  db-geofencing:
    image: mysql:8.0
    container_name: db-geofencing
    environment:
      MYSQL_DATABASE: db_geofencing
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
  #------------------

  # 4. Frontend
  frontend:
    build: ./frontend/careTemplate
    container_name: app_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mongo_data: